### ISSUE TITLE
Binary sign giving an error

### ISSUE THREAD

**Issue by SachaEpskamp** [jmbh/mgm#13] opened 2020-05-18 08:05 UTC
I get the following error routinely when using `binarySign = TRUE`:
 ```
Error in sign(l_w_par[[1]][2]) : 
  non-numeric argument to mathematical function 
```
Here is a reproducible example (I hope):
```
set.seed(2)
res <- mgm(matrix(sample(0:1,300,TRUE),100,3), type = rep("c",3), level = rep(2,3), binarySign = TRUE)
```

**Comment by jmbh** [comment] 2020-05-19 07:43
Hi Sacha, 

I cannot reproduce this error. Are you using the latest devel version from Github (1.2-10)?

Jonas

**Comment by SachaEpskamp** [comment] 2020-05-19 07:53
Probably an architecture thing then. Try with this [dataset ](http://sachaepskamp.com/files/mgmdata.csv) and 

```
data <- read.csv("mgmdata.csv")
res <- mgm(data, type = rep("c",3), level = rep(2,3), binarySign = TRUE)

```

**Comment by jmbh** [comment] 2020-05-19 10:04
Still no error ...

**Comment by SachaEpskamp** [comment] 2020-05-19 10:07
I am using R 4.0.0, perhaps it is a recent thing?

**Comment by jmbh** [comment] 2020-05-19 11:03
I use R 3.6.0, so that could be it.

**Comment by SachaEpskamp** [comment] 2020-06-04 13:11
Hi Jonas, any update on this?

**Comment by AdelaIsvoranu** [comment] 2020-06-10 10:57
Hi Jonas,

I am getting the same error today. I am also using R 4.0.0:
Error in sign(l_w_par[[1]][2]) : 
  non-numeric argument to mathematical function

Any idea why it may happen, how to fix it?

**Comment by jmbh** [comment] 2020-06-22 09:21
The problem was indeed the switch to R 4.0.0. 

Now fixed!

**Closed as completed by jmbh** 2020-06-22 09:21 UTC
